services:
  line-provider:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: line-provider
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - line-provider-network

  mongo:
    image: mongo:5.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - line-provider-network

volumes:
  mongo_data:


networks:
  line-provider-network:
    driver: bridge
